#!/bin/sh
sudo ssh -i /etc/test-instance-aws.pem ubuntu@ec2-13-212-19-3.ap-southeast-1.compute.amazonaws.com <<EOF
    cd ~/dd-reborn-micro
    git pull origin master
    sudo docker-compose up -d
    exit
EOF
